title: jeanputz roxx
author: jeanputz
email: jeanpuzt@jeanputz.com
description: > # this means to ignore newlines until "baseurl:"
  super awesome descritpion


show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
